### ISSUE TITLE
feature request: let user choose from installed apps

### ISSUE THREAD

**Issue by raylinger** [erikstam/uninstaller#44]
(sorry i don't know how to "contribute")

i added a part where the user gets prompted by the applications installed in the /Applictaions Folder and excluded out of scope software
Of course this will only work if the labels are implemented, but i think this will build up, it's very useful script to let standard Users get rid of software without beeing admin.

First comment or delete these sections:
```
#################
#if [[ -n "$1" ]]; then
#  label=$1
#else
#  label="$selected_app_name"
#fi

#if [[ $# -eq 0 ]]; then
  # "no label as argument -> show all labels
#  grep -E '^[a-z0-9\_-]*(\)|\|\\)$' "$0" | tr -d ')' | sort
#  exit 0
#fi

# check for root
#if [ "$(whoami)" != "root" ]; then
#  echo "not running as root, exiting"
#  exit 1
#fi
#################
```

then add this .... right before 

```
# Check which event is triggered and add extra information.
case $label in
```

```
##################

# Define the path to the Applications folder
applications_folder="/Applications"

# Create an empty array to store app names
APPS=()

# List all .app files in the Applications folder
while IFS= read -r app_path; do
    # Extract the app name without folder names or white spaces
    app_name=$(basename "$app_path")
    
    # Apps that should be excluded from uninstallation List
    excluded_apps=("Terminal.app" "Self Service.app" "Support.app" "DEPNotify.app" "Company Portal.app" "Color Picker.app" "Jamf Connect.app" "UninstallApplication.app" "Microsoft Defender.app")

    # Check if the app name is in the excluded_apps list
    if [[ ! " ${excluded_apps[@]} " =~ " $app_name " ]]; then
        # Append the app name to the app_names array
        APPS+=("$app_name")
    fi
done < <(find "$applications_folder" -name "*.app" -type d -maxdepth 2)

# Sort the app names alphabetically
IFS=$'\n' sorted_apps=($(sort <<<"${APPS[*]}"))
unset IFS

# Display the list and get the selected app
selected_app=$(osascript -e "set ASlist to the paragraphs of \"$(printf '%s\n' "${sorted_apps[@]}")\"" -e 'return choose from list ASlist with prompt "Select the application you want to uninstall:"')

# Remove the .app extension and any whitespace from the selected app
label=$(echo "$selected_app" | tr '[:upper:]' '[:lower:]' | sed 's/ //g' | sed 's/.app//g')

# Lowercase the label
label=${label:l}

# Debugging: Print the label
echo "Label: $label"
```

**Comment by MacMike077** [comment]
Hi raylinger.

Thank you very much for your contribution and the time you invested in improving this code. We appreciate your efforts.

At first, this seemed like a good idea; however, you can only delete files that you own unless you are an administrator. One of the main purposes of the uninstaller is to remove LaunchDaemons and helper files.
As a standard user, you cannot delete these files by default, as they are typically owned by root. This limitation means that the uninstaller cannot fully complete its job because not all files can be deleted. Therefore, the uninstaller really needs to run as root. So for now we cannot implement this change.

However, we value your input and hope to see more of your ideas in the future. Thanks again for your understanding and interest in contributing!

**Comment by MacMike077** [comment]
Closed

**Comment by raylinger** [comment]
thanks!

well i don‘t understand your comment. i did not change anything in the core script. i just let the user choose from a list of installed apps.
If the script runs from i.e. Jamf Self Service it still runs as root.

For me it works.. Thanks anyway :)
